//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace starrexam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public string bookingId { get; set; }
        public short roomNumber { get; set; }
        public string userName { get; set; }
        public System.DateTime starting { get; set; }
        public System.DateTime ending { get; set; }
    
        public virtual room room { get; set; }
        public virtual user user { get; set; }
    }
}
